### ISSUE TITLE
UnicodeDecodeError with anything but goldrun.ym

### ISSUE THREAD

**Issue by quarterturn** [eqy/ymduino#2]
decode.py works fine with 'goldrun.ym' but nothing else (so far). Where did you get the ym file or what did you do to 'convert' it? Your code doesn't like my .mym files either. They work fine when streamed over serial though.

**Comment by eqy** [comment]
Are you decoding ym files directly or extracting them from lha compression first? The decoder expects files to be extracted already (e.g., with lha x myfile.ym).

**Comment by quarterturn** [comment]
They're already in .ym format. Here's an example of a collection I tried: http://bulba.untergrund.net/faveym.7z

**Comment by eqy** [comment]
Those files look too small to be extracted, the ym format uses LHA compression, and I verified by opening one of the files with 7zip. 
That is, I extracted the 7z archive, and then extracted one of the individual files again.
Have you tried extracting the ym file to produce the compressed contents? (sorry for the confusion)

You can read about the compression here:
https://github.com/skeezix/zikzak/blob/master/zik80/audio-gen/ym-file-format.txt

**Comment by quarterturn** [comment]
Ah got it. I extracted the ym files and then ran them through decode.py. They play now. Thanks!
